// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YMYP4EntityFramwork.CodeFirstWinForm.DAL;

#nullable disable

namespace YMYP4EntityFramwork.CodeFirstWinForm.Migrations
{
    [DbContext(typeof(CodeFirstDbContext))]
    [Migration("20250112110311_DenemeSeedFill2")]
    partial class DenemeSeedFill2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cep Telefonu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Televizyon"
                        });
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Deneme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Denemes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description - 1",
                            Name = "Name - 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description - 2",
                            Name = "Name - 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description - 3",
                            Name = "Name - 3"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description - 4",
                            Name = "Name - 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description - 5",
                            Name = "Name - 5"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description - 6",
                            Name = "Name - 6"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description - 7",
                            Name = "Name - 7"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description - 8",
                            Name = "Name - 8"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description - 9",
                            Name = "Name - 9"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description - 10",
                            Name = "Name - 10"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description - 11",
                            Name = "Name - 11"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description - 12",
                            Name = "Name - 12"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description - 13",
                            Name = "Name - 13"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description - 14",
                            Name = "Name - 14"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description - 15",
                            Name = "Name - 15"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Description - 16",
                            Name = "Name - 16"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Description - 17",
                            Name = "Name - 17"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Description - 18",
                            Name = "Name - 18"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Description - 19",
                            Name = "Name - 19"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Description - 20",
                            Name = "Name - 20"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Description - 21",
                            Name = "Name - 21"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Description - 22",
                            Name = "Name - 22"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Description - 23",
                            Name = "Name - 23"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Description - 24",
                            Name = "Name - 24"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Description - 25",
                            Name = "Name - 25"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Description - 26",
                            Name = "Name - 26"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Description - 27",
                            Name = "Name - 27"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Description - 28",
                            Name = "Name - 28"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Description - 29",
                            Name = "Name - 29"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Description - 30",
                            Name = "Name - 30"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Description - 31",
                            Name = "Name - 31"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Description - 32",
                            Name = "Name - 32"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Description - 33",
                            Name = "Name - 33"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Description - 34",
                            Name = "Name - 34"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Description - 35",
                            Name = "Name - 35"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Description - 36",
                            Name = "Name - 36"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Description - 37",
                            Name = "Name - 37"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Description - 38",
                            Name = "Name - 38"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Description - 39",
                            Name = "Name - 39"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Description - 40",
                            Name = "Name - 40"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Description - 41",
                            Name = "Name - 41"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Description - 42",
                            Name = "Name - 42"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Description - 43",
                            Name = "Name - 43"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Description - 44",
                            Name = "Name - 44"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Description - 45",
                            Name = "Name - 45"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Description - 46",
                            Name = "Name - 46"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Description - 47",
                            Name = "Name - 47"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Description - 48",
                            Name = "Name - 48"
                        },
                        new
                        {
                            Id = 49,
                            Description = "Description - 49",
                            Name = "Name - 49"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Description - 50",
                            Name = "Name - 50"
                        },
                        new
                        {
                            Id = 51,
                            Description = "Description - 51",
                            Name = "Name - 51"
                        },
                        new
                        {
                            Id = 52,
                            Description = "Description - 52",
                            Name = "Name - 52"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Description - 53",
                            Name = "Name - 53"
                        },
                        new
                        {
                            Id = 54,
                            Description = "Description - 54",
                            Name = "Name - 54"
                        },
                        new
                        {
                            Id = 55,
                            Description = "Description - 55",
                            Name = "Name - 55"
                        },
                        new
                        {
                            Id = 56,
                            Description = "Description - 56",
                            Name = "Name - 56"
                        },
                        new
                        {
                            Id = 57,
                            Description = "Description - 57",
                            Name = "Name - 57"
                        },
                        new
                        {
                            Id = 58,
                            Description = "Description - 58",
                            Name = "Name - 58"
                        },
                        new
                        {
                            Id = 59,
                            Description = "Description - 59",
                            Name = "Name - 59"
                        },
                        new
                        {
                            Id = 60,
                            Description = "Description - 60",
                            Name = "Name - 60"
                        },
                        new
                        {
                            Id = 61,
                            Description = "Description - 61",
                            Name = "Name - 61"
                        },
                        new
                        {
                            Id = 62,
                            Description = "Description - 62",
                            Name = "Name - 62"
                        },
                        new
                        {
                            Id = 63,
                            Description = "Description - 63",
                            Name = "Name - 63"
                        },
                        new
                        {
                            Id = 64,
                            Description = "Description - 64",
                            Name = "Name - 64"
                        },
                        new
                        {
                            Id = 65,
                            Description = "Description - 65",
                            Name = "Name - 65"
                        },
                        new
                        {
                            Id = 66,
                            Description = "Description - 66",
                            Name = "Name - 66"
                        },
                        new
                        {
                            Id = 67,
                            Description = "Description - 67",
                            Name = "Name - 67"
                        },
                        new
                        {
                            Id = 68,
                            Description = "Description - 68",
                            Name = "Name - 68"
                        },
                        new
                        {
                            Id = 69,
                            Description = "Description - 69",
                            Name = "Name - 69"
                        },
                        new
                        {
                            Id = 70,
                            Description = "Description - 70",
                            Name = "Name - 70"
                        },
                        new
                        {
                            Id = 71,
                            Description = "Description - 71",
                            Name = "Name - 71"
                        },
                        new
                        {
                            Id = 72,
                            Description = "Description - 72",
                            Name = "Name - 72"
                        },
                        new
                        {
                            Id = 73,
                            Description = "Description - 73",
                            Name = "Name - 73"
                        },
                        new
                        {
                            Id = 74,
                            Description = "Description - 74",
                            Name = "Name - 74"
                        },
                        new
                        {
                            Id = 75,
                            Description = "Description - 75",
                            Name = "Name - 75"
                        },
                        new
                        {
                            Id = 76,
                            Description = "Description - 76",
                            Name = "Name - 76"
                        },
                        new
                        {
                            Id = 77,
                            Description = "Description - 77",
                            Name = "Name - 77"
                        },
                        new
                        {
                            Id = 78,
                            Description = "Description - 78",
                            Name = "Name - 78"
                        },
                        new
                        {
                            Id = 79,
                            Description = "Description - 79",
                            Name = "Name - 79"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Description - 80",
                            Name = "Name - 80"
                        },
                        new
                        {
                            Id = 81,
                            Description = "Description - 81",
                            Name = "Name - 81"
                        },
                        new
                        {
                            Id = 82,
                            Description = "Description - 82",
                            Name = "Name - 82"
                        },
                        new
                        {
                            Id = 83,
                            Description = "Description - 83",
                            Name = "Name - 83"
                        },
                        new
                        {
                            Id = 84,
                            Description = "Description - 84",
                            Name = "Name - 84"
                        },
                        new
                        {
                            Id = 85,
                            Description = "Description - 85",
                            Name = "Name - 85"
                        },
                        new
                        {
                            Id = 86,
                            Description = "Description - 86",
                            Name = "Name - 86"
                        },
                        new
                        {
                            Id = 87,
                            Description = "Description - 87",
                            Name = "Name - 87"
                        },
                        new
                        {
                            Id = 88,
                            Description = "Description - 88",
                            Name = "Name - 88"
                        },
                        new
                        {
                            Id = 89,
                            Description = "Description - 89",
                            Name = "Name - 89"
                        },
                        new
                        {
                            Id = 90,
                            Description = "Description - 90",
                            Name = "Name - 90"
                        },
                        new
                        {
                            Id = 91,
                            Description = "Description - 91",
                            Name = "Name - 91"
                        },
                        new
                        {
                            Id = 92,
                            Description = "Description - 92",
                            Name = "Name - 92"
                        },
                        new
                        {
                            Id = 93,
                            Description = "Description - 93",
                            Name = "Name - 93"
                        },
                        new
                        {
                            Id = 94,
                            Description = "Description - 94",
                            Name = "Name - 94"
                        },
                        new
                        {
                            Id = 95,
                            Description = "Description - 95",
                            Name = "Name - 95"
                        },
                        new
                        {
                            Id = 96,
                            Description = "Description - 96",
                            Name = "Name - 96"
                        },
                        new
                        {
                            Id = 97,
                            Description = "Description - 97",
                            Name = "Name - 97"
                        },
                        new
                        {
                            Id = 98,
                            Description = "Description - 98",
                            Name = "Name - 98"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Description - 99",
                            Name = "Name - 99"
                        },
                        new
                        {
                            Id = 100,
                            Description = "Description - 100",
                            Name = "Name - 100"
                        });
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Core I7 9900 16Gb ram 8Gb Ekran Kartı",
                            Name = "Toshiba Laptop",
                            Price = 15000m,
                            Stock = 11
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Core I5 9800 16Gb ram 4Gb Ekran Kartı",
                            Name = "HP Laptop",
                            Price = 13000m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Core I3 9900 8Gb ram 8Gb Ekran Kartı",
                            Name = "Casper Desktop",
                            Price = 10000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Core I5 9000 8Gb ram 8Gb Ekran Kartı",
                            Name = "Lenovo Desktop",
                            Price = 13000m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "256Gb Hafıza",
                            Name = "IPhone 15",
                            Price = 15000m,
                            Stock = 17
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "512Gb Hafıza",
                            Name = "Samsung S20",
                            Price = 14000m,
                            Stock = 19
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "55\"",
                            Name = "LG Televizyon",
                            Price = 12500m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Order", b =>
                {
                    b.HasOne("YMYP4EntityFramwork.CodeFirstWinForm.DAL.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Product", b =>
                {
                    b.HasOne("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.ProductFeature", b =>
                {
                    b.HasOne("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("YMYP4EntityFramwork.CodeFirstWinForm.DAL.ProductFeature", "ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.Product", b =>
                {
                    b.Navigation("ProductFeature")
                        .IsRequired();
                });

            modelBuilder.Entity("YMYP4EntityFramwork.CodeFirstWinForm.DAL.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
